import React from "react";
import { useState } from "react";
import classes from "./Planner.module.css"
import WeekSelector from "./WeekSelector"
import Week from "./Week.js"
const Planner = (props) => {
    const weeksArray = [
        {
            period: "۲۶ تیر - ۱ مرداد",
            days: [
                {
                    name: "شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "یکشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "دوشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "سه شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "چهارشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "پنج شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "جمعه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
            ]
        },
        {
            period: "۲ تیر - ۸ تیر",
            days: [
                {
                    name: "شنبه",
                    breakfastName: "املت",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "قرمه سبزی",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "یکشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "دوشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "سه شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "چهارشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "پنج شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "جمعه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
            ]

        },
        {
            period: "۹ تیر - ۱۵ تیر",
            days: [
                {
                    name: "شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "یکشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "دوشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "سه شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "چهارشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "پنج شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "جمعه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
            ]

        },
        {
            period: "۱۶ تیر - ۲۲ تیر",
            days: [
                {
                    name: "شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "یکشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "دوشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "سه شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "چهارشنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "پنج شنبه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
                {
                    name: "جمعه",
                    breakfastName: "",
                    breakfastImageUrl: "",
                    breakfastlink: "",
                    lunchName: "",
                    lunchImageUrl: "",
                    lunchlink: "",
                    dinnerName: "",
                    dinnerImageUrl: "",
                    dinnerfastlink: "",
                },
            ]

        }
    ]
    const [displayingWeekVar, setDisplayingWeekVar] = useState(1);
    const changeDisplayingWeekVar = (value) => {
        setDisplayingWeekVar(prevvalue => prevvalue + value);
    }
    return (
        <div>
            <WeekSelector weeks={weeksArray} displayingWeek={displayingWeekVar} setDisplayingWeek={changeDisplayingWeekVar} />
            <Week weekData={weeksArray[displayingWeekVar]}></Week>
        </div>
    );
}

export default Planner;